### PR TITLE
Add paypal tests & description optional values

### PR DESCRIPTION
**Pull request by molinto**

### CODE REVIEW

**Comment by mikemaccana** [comment]
Thanks Sharry! I'm not doing much with Quaderno ATM - would you like to take over the project?

**Comment by molinto** [comment]
No probs. Sure thing, if you don't mind.

**Comment by molinto** [comment]
How is it best to progress please?

**Comment by mikemaccana** [comment]
Hi Sharry, I'll work out what I need to do from this end. 
Thanks for taking over - my new startup focuses on EV SSL certs and there is no VAT on digital goods!

On Tue, Jun 30, 2015 at 5:19 AM -0700, "Sharry Stowell" notifications@github.com wrote:

How is it best to progress please?

**Comment by molinto** [comment]
We are only getting started with the VAT Moss mess lol

**Pull request merged**
